supports_swift_versions '>= 5.0'
use_frameworks!
platform :osx, "10.15"

target 'PahkatClient_Tests' do
  pod 'PahkatClient', :path => '../'
  
end

target 'PahkatClient_Example' do
  pod 'PahkatClient', :path => '../'
  
end

